import "@/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <script
        async
        src="https://analytics.paulvanderlei.com/script.js"
        data-website-id="3fed5c7f-03cf-467e-88ec-31bb6bddc6af"
      ></script>
      <body className={`font-sans ${inter.variable}`}>{children}</body>
    </html>
  );
}
